#!/bin/sh
alias h='history'
alias 1='fg %1'
alias 2='fg %2'
alias 3='fg %3'
alias k1='kill -HUP %1 && fg'
alias k2='kill -HUP %2 && fg'
alias k3='kill -HUP %3 && fg'

alias trim='cut -c-$(tput cols)'

# blue+bold in solarized palette is gray
#alias rg='rg --smart-case --colors path:fg:blue --colors path:style:bold --colors line:none'
#alias ag='ag --color-path "1;36" --color-match "1;31" --color-line-number "0"'
alias rg='rg --smart-case'

alias ale='alembic'
alias d='docker'
alias dc='docker-compose'
alias dk='docker stack'
alias ds='docker service'
alias g='git'
alias gc='gcloud'
alias gsu='gsutil'
alias kc='kubectl'
alias po='poetry'
alias tf='terraform'

# -- commands not in path
alias mvn='~/workspace/java/maven/bin/mvn'
alias ant='~/workspace/java/ant/bin/ant'

# -- long commands
# https://www.commandlinefu.com/commands/view/12043/remove-color-special-escape-ansi-codes-from-text-with-sed
alias stripansi='sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"'
alias top10='/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10'
alias brewup='brew update && brew upgrade && brew cleanup -s'
alias tagspy='ctags -R --fields=+l --languages=python --python-kinds=-iv $(python -c "import os, sys; print('"'"' '"'"'.join('"'"'{}'"'"'.format(d) for d in sys.path if os.path.isdir(d)))")'
alias uenc='python -c "import sys,urllib;print urllib.quote(sys.stdin.read().strip())"'
alias udec='python -c "import sys,urllib;print urllib.unquote(sys.stdin.read().strip())"'


## -- complete alias

# https://ubuntuforums.org/showthread.php?t=733397
# Date   : 23.03.2008
make_completion_wrapper() {
	local function_name="$2"
	local arg_count=$(($#-3))
	local comp_function_name="$1"
	shift 2
	local function="
function $function_name {
	((COMP_CWORD+=$arg_count))
	COMP_WORDS=( "$@" \${COMP_WORDS[@]:1} )
	"$comp_function_name"
	return 0
}"
	eval "$function"
	#echo "$function"
}

__git_complete g __git_main
complete -o default -F __start_kubectl kc
complete -C /usr/local/bin/aws_completer aws
make_completion_wrapper  "_python_argcomplete gcloud" _gcloud gcloud
complete -o nospace -F _gcloud gc
complete -C terraform terraform
complete -C terraform tf
complete -F _docker d

## --- local
