#!/bin/sh
alias h='history'
alias 1='fg %1'
alias 2='fg %2'
alias 3='fg %3'
alias k1='kill -HUP %1 && fg'
alias k2='kill -HUP %2 && fg'
alias k3='kill -HUP %3 && fg'

alias ls='ls -F --color=always'
[ "$(uname -s)" = "Darwin" ] && alias ls='ls -F'
alias rm-all='rm -Ir'
alias trim='cut -c-$(tput cols)'

alias g='git'
alias gd='git diff'
alias gst='git status'

alias ag='ag --color-path "1;36" --color-match "1;31" --color-line-number "0"'
# blue+bold in solarized palette is gray
alias rg='rg --smart-case --colors path:fg:blue --colors path:style:bold --colors line:none'

# https://www.commandlinefu.com/commands/view/12043/remove-color-special-escape-ansi-codes-from-text-with-sed
alias stripansi='sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"'
alias top10='/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10'
alias brewup='brew update && brew upgrade && brew cleanup -s'

alias uenc='python -c "import sys,urllib;print urllib.quote(sys.stdin.read().strip())"'
alias udec='python -c "import sys,urllib;print urllib.unquote(sys.stdin.read().strip())"'

alias po='poetry'
alias tagspy='ctags -R --fields=+l --languages=python --python-kinds=-iv $(python -c "import os, sys; print('"'"' '"'"'.join('"'"'{}'"'"'.format(d) for d in sys.path if os.path.isdir(d)))")'

# kube/docker

alias d='docker'
alias compose='docker-compose'

alias gc='gcloud'

alias kc='kubectl'
alias km='minikube'
alias kcgp='kubectl get pods'
alias kcgpw='kubectl get pods -o wide'
alias kcgs='kubectl get services'
alias kcgsw='kubectl get services -o wide'

# common typos
alias maek='make'

# java
alias mvn='~/workspace/java/maven/bin/mvn'
alias ant='~/workspace/java/ant/bin/ant'

## --- local
