## called from ~/.bashrc

export TERM_ITALICS=true
#export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

if [ "$(uname -s)" = "Darwin" ]; then
	export CLICOLOR=1
	export GREP_OPTIONS='--color=auto'
	export LSCOLORS=exfxcxdxbxegedabagacad

	# http://drmuey.com/?do=page&id=15
	export COPYFILE_DISABLE=true
fi

## completion

## git bash completion, before general bash_completion b/c tig completion script
[ "$(uname -s)" = "Darwin" ] && XCODE_PRE=$(xcode-select -p)
for f in $XCODE_PRE/usr/share/git-core/git-completion.bash \
		$XCODE_PRE/usr/share/git-core/git-prompt.sh \
		"/usr/share/git-core/contrib/completion/git-prompt.sh" \
		"/etc/bash_completion.d/git-prompt"; do
	[ -f "$f" ] && source $f
done
# bash-completion, which calls installed scripts in .../bash_completion.d/
for f in /etc/bash_completion /usr/share/bash-completion/bash_completion; do
	[ -f "$f" ] && source $f
done

[ -x "$(command -v pipenv)" ] && eval "$(pipenv --completion)"

hash terraform 2>/dev/null && complete -C terraform terraform
for f in `ls ~/.bash/bash_completion.d`; do
	source ~/.bash/bash_completion.d/$f
done

# fzf
[ -f ~/.fzf.bash ] && . ~/.fzf.bash
## https://mike.place/2017/fzf-fd/
## ubuntu installs as "fdfind"
type "fdfind" &>/dev/null && fd=fdfind || fd=fd
export FZF_DEFAULT_COMMAND="$fd -t f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$fd -t d"

# set the bash prompt (uses fzf, git from above)
source ~/.bash/prompt

# History (after setting bash prompt)
# See bash(1) for more options
shopt -s histappend
export HISTCONTROL=ignorespace:ignoredups:erasedups
export HISTSIZE=100000
export HISTFILESIZE=200000
export HISTIGNORE="&:[ ]*:exit:ls:tree:bg:fg:k1:history:clear:g pull:gst"

# autojump
if [ -f "/etc/profile.d/autojump.sh" ]; then
	. /etc/profile.d/autojump.sh
elif [ -f "/usr/local/etc/profile.d/autojump.sh" ]; then
	. /usr/local/etc/profile.d/autojump.sh
elif [ -f "/usr/share/autojump/autojump.sh" ]; then
	. /usr/share/autojump/autojump.sh
fi

# tmux
[ "$SESSION_TYPE" = "remote/ssh" ] && \
	export TMUX_SYM='🔒' || \
	export TMUX_SYM='⚡'

source "$HOME/.bash/aliases"
source "$HOME/.bash/complete_alias"

## --- local
